### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by Lui22**
Make installation guide more clear by adding `publish` commands

### CODE REVIEW

**Comment by Vyachee** [comment]
Support! Lenin handsome

**Comment by TiiFuchs** [comment]
There is no need to publish those configuration files. Only if you want to change something. But I agree, that we should include it in the README.

But the Installation section is the wrong place for it.

**Comment by Lui22** [comment]
> There is no need to publish those configuration files. Only if you want to change something. But I agree, that we should include it in the README.
> 
> But the Installation section is the wrong place for it.

But without publishing I wasn't able to use library

**Comment by TiiFuchs** [comment]
Then something went wrong. 

Laravel auto-discovers the ServiceProvider which loads the files from the vendor folder if you didn't publish it.

**Comment by noplanman** [comment]
@TiiFuchs Where should those instructions go? Maybe we can merge here and then move them in a next version?

**Comment by TiiFuchs** [comment]
The changed proposed here, are not the right way IMHO.
I agree, that we should add a few things to the readme, and I'd do that, but I need to check it out and test a few things, because I myself no longer know exactly how everything works. 🙈 

I will close this, and add an issue for the improved readme instructions

**Pull request closed without merging**
