### PR TITLE
Update package to fix Monolog version problem.

### LINKED ISSUE #11: Problem with Laravel 6.6.0
I have created a project with Laravel 6.6.0 and require the library with command ```composer require php-telegram-bot/laravel```. The error occurs.

```
$ composer require php-telegram-bot/laravel
Using version ^1.1 for php-telegram-bot/laravel
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for monolog/monolog (locked at 2.0.1) -> satisfiable by monolog/monolog[2.0.1].
    - php-telegram-bot/laravel 1.1.0 requires longman/telegram-bot ^0.60 -> satisfiable by longman/telegram-bot[0.60.0].
    - php-telegram-bot/laravel 1.1.1 requires longman/telegram-bot ^0.60 -> satisfiable by longman/telegram-bot[0.60.0].
    - Conclusion: don't install longman/telegram-bot 0.60.0
    - Installation request for php-telegram-bot/laravel ^1.1 -> satisfiable by php-telegram-bot/laravel[1.1.0, 1.1.1].


Installation failed, reverting ./composer.json to its original content.
```

### PR DESCRIPTION
**Pull request by littpi**
Fix #11.

### CODE REVIEW

**Comment by sitenzo** [comment]
How to install this fix.
when i want to install i get following error 

image

**Comment by noplanman** [comment]
@sitenzo Make sure you use version 0.61 and above :+1:

**Comment by sitenzo** [comment]
@noplanman How can i use 0.61, in my composer i have "php-telegram-bot/laravel": "^1.1.1" there is no update available and i'm on version 0.60 see my settings in issue [#548473794](https://github.com/php-telegram-bot/laravel/issues/13#issue-548473794)

**Comment by noplanman** [comment]
@sitenzo To define a specific version to be used you can use the following in your `composer.json`:

```json
"require": {
    "php-telegram-bot/laravel": "^1.1.1",
    "longman/telegram-bot": "0.61 as 0.60"
}
```

This will tell composer to use version `0.61` in place of `0.60`.

I'll upate this by default with the next release 👍

**Pull request merged**
